export type BreadcrumbRouteConfig = {
    title: string;
    parent?: string;
};

export const breadcrumbRouteConfig: Record<string, BreadcrumbRouteConfig> = {
    'admin.dashboard': { title: 'Dashboard' },
    'admin.emi.requests': { title: 'EMI Requests' },
    'admin.emi.requests.detail': { title: 'EMI Request Detail', parent: 'admin.emi.requests' },
    'admin.emi.users': { title: 'EMI Users' },
    'admin.orders.list': { title: 'All Orders' },
    'admin.orders.detail': { title: 'Order Detail', parent: 'admin.orders.list' },
    'admin.orders.pre': { title: 'Pre Orders' },
    'admin.orders.cart': { title: 'Cart Items' },
    'admin.orders.wish': { title: 'Wish Pot' },
    'admin.customers.list': { title: 'Customers' },
    'admin.customers.detail': { title: 'Customer Detail', parent: 'admin.customers.list' },
    'admin.product.list': { title: 'Products' },
    'admin.product.reviews': { title: 'Product Reviews', parent: 'admin.product.list' },
    'admin.product.create': { title: 'Create Product', parent: 'admin.product.list' },
    'admin.product.detail': { title: 'Product Detail', parent: 'admin.product.list' },
    'admin.product.edit': { title: 'Edit Product', parent: 'admin.product.list' },
    'admin.product.categories': { title: 'Categories' },
    'admin.product.categories.detail': { title: 'Category Detail', parent: 'admin.product.categories' },
    'admin.product.brands': { title: 'Brands' },
    'admin.product.brands.detail': { title: 'Brand Detail', parent: 'admin.product.brands' },
    'admin.product.attributes': { title: 'Attributes' },
    'admin.treks.regions': { title: 'Regions' },
    'admin.treks.list': { title: 'Tour / Treks' },
    'admin.treks.fixed.departure': { title: 'Fixed Departure' },
    'admin.treks.guide.profile': { title: 'Guide Profile' },
    'admin.blogs.list': { title: 'All Blogs' },
    'admin.blogs.create': { title: 'Create Blog', parent: 'admin.blogs.list' },
    'admin.blogs.detail': { title: 'Blog Detail', parent: 'admin.blogs.list' },
    'admin.blogs.edit': { title: 'Edit Blog', parent: 'admin.blogs.list' },
    'admin.blogCategories.list': { title: 'Blog Categories' },
    'admin.blogCategories.detail': { title: 'Blog Category Detail', parent: 'admin.blogCategories.list' },
    'admin.banners.list': { title: 'Banners' },
    'admin.banners.detail': { title: 'Banner Detail', parent: 'admin.banners.list' },
    'admin.campaigns.list': { title: 'Campaigns' },
    'admin.pages.list': { title: 'Pages' },
    'admin.inquiries.list': { title: 'Inquiries' },
    'admin.users.list': { title: 'User Lists' },
    'admin.faqs.list': { title: 'FAQs Management' },
    'admin.paymentMethods.list': { title: 'Payment Methods' },
    'admin.paymentMethods.detail': { title: 'Payment Method Detail', parent: 'admin.paymentMethods.list' },
    'admin.list': { title: 'Admin Management' },
    'admin.roles.manage': { title: 'Role Management' },
    'admin.files.list': { title: 'Files' },
    'admin.developer': { title: 'Developer' },
    'admin.settings': { title: 'Settings' },
};
